//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Exam_Project_Main.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Exam_QuizEntities : DbContext
    {
        public Exam_QuizEntities()
            : base("name=Exam_QuizEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin_tbl> Admin_tbl { get; set; }
        public DbSet<Candidate_tbl> Candidate_tbl { get; set; }
        public DbSet<Exam_tbl> Exam_tbl { get; set; }
        public DbSet<Questions_tbl> Questions_tbl { get; set; }
        public DbSet<Result_tbl> Result_tbl { get; set; }
        public DbSet<Subject_tbl> Subject_tbl { get; set; }
    }
}
